---
repos:
  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.8.4
    hooks:
      - id: flake8
        language_version: python3
        args: ['--config=setup.cfg']
        pass_filenames: false
